### ISSUE TITLE
 Could not resolve dependencies for project

### ISSUE THREAD

**Issue by Cassiel1987** [elbosso/rfc3161timestampingserver#11]
The following artifacts could not be resolved: de.elbosso:algorithms:jar:1.1.0-SNAPSHOT, de.elbosso:data:jar:1.1.0-SNAPSHOT, de.elbosso:documents:jar:1.1.0-SNAPSHOT, de.elbosso:custommaterialgfx: Could not pull thedependencies

**Comment by elbosso** [comment]
I suspect that you used one of the releases and not the trunk - i tested and it appears that i forgot to draft a new release after my last changes (got sidetracked somehow). With the new release i drafted just now (https://github.com/elbosso/rfc3161timestampingserver/releases/tag/rfc3161timestampingserver-1.1.0), all should work well. If it does not - please dont hesitate to contact me again (it would also be nice if you could just drop me a short comment if it works for you too) Sorry again for the inconvenience!
